// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views_convert

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "tudo-tools/templates"

func Distance(htmxReq bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form class=\"flex flex-col w-fit\" hx-post=\"/convert-distance\" hx-target=\"#output_value\" hx-swap=\"innerHTML\"><div class=\"flex gap-2 justify-between w-full\"><label for=\"input_value\"></label> <input id=\"input_value\" name=\"input_value\" placeholder=\"Valor de origem\" type=\"number\"> <label for=\"input_unit\"></label> <select id=\"input_unit\" name=\"input_unit\"><option>Milímetro</option> <option>Centímetro</option> <option>Decímetro</option> <option>Metro</option> <option>Decâmetro</option> <option>Hecâmetro</option> <option>Kilômetro</option></select></div><div class=\"flex gap-2 mt-2 justify-between w-full\"><span id=\"output_value\">Valor convertido</span> <label for=\"output_unit\"></label> <select id=\"output_unit\" name=\"output_unit\"><option>Milímetro</option> <option>Centímetro</option> <option>Decímetro</option> <option>Metro</option> <option>Decâmetro</option> <option>Hecâmetro</option> <option>Kilômetro</option></select></div><button class=\"mt-4\" type=\"submit\">Converter</button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = templates.Base("", htmxReq).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
